FROM debian:buster

# Instalar dependencias adicionales
RUN apt-get update && apt-get install -y wget curl openjdk-11-jre procps

RUN apt-get update \
 && apt-get install -y locales \
 && dpkg-reconfigure -f noninteractive locales \
 && locale-gen C.UTF-8 \
 && /usr/sbin/update-locale LANG=C.UTF-8 \
 && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
 && locale-gen \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Users with other locales should set this in their derivative image
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update \
 && apt-get install -y curl unzip \
    python3 python3-setuptools \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && apt-get install -y python3-pip \
 && pip3 install py4j \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# JAVA
RUN apt-get update \
 && apt-get install -y openjdk-11-jre \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# HADOOP
ENV HADOOP_VERSION 3.3.6
ENV HADOOP_HOME /usr/hadoop-$HADOOP_VERSION
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
ENV PATH $PATH:$HADOOP_HOME/bin
RUN curl -sL --retry 3 \
  "https://dlcdn.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6-src.tar.gz" \
  | gunzip \
  | tar -x -C /usr/ \
 && rm -rf $HADOOP_HOME/share/doc 

# SPARK
ENV SPARK_VERSION 3.5.1
ENV SPARK_PACKAGE spark-${SPARK_VERSION}-bin-without-hadoop
ENV SPARK_HOME /usr/spark-${SPARK_VERSION}

# Configurar puertos específicos en Spark
ENV SPARK_DRIVER_PORT=7001
ENV SPARK_UI_PORT=4040
ENV SPARK_BLOCKMANAGER_PORT=7005

ENV SPARK_HOME=${SPARK_HOME:-"/opt/spark"}
ENV HADOOP_HOME=${HADOOP_HOME:-"/opt/hadoop"}

ENV SPARK_DIST_CLASSPATH="$HADOOP_HOME/etc/hadoop/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/tools/lib/*"
ENV PATH $PATH:${SPARK_HOME}/bin
RUN curl -sL --retry 3 "https://dlcdn.apache.org/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz" -o spark-3.5.1-bin-hadoop3.tgz \
    && tar xzf spark-3.5.1-bin-hadoop3.tgz -C /usr/ \
    && ls -l /usr/ \
    && mv /usr/spark-3.5.1-bin-hadoop3 /usr/spark-3.5.1 \
    && ls -l /usr/

# SQOOP
ENV SQOOP_VERSION 1.4.7
ENV SQOOP_HOME /usr/sqoop-${SQOOP_VERSION}
ENV PATH $PATH:${SQOOP_HOME}/bin

# Separar comandos para descargar y extraer Sqoop, y depurar
RUN curl -sL --retry 3 "https://dlcdn.apache.org/sqoop/${SQOOP_VERSION}/sqoop-${SQOOP_VERSION}.tar.gz" -o sqoop-${SQOOP_VERSION}.tar.gz \
    && file sqoop-${SQOOP_VERSION}.tar.gz \
    && cat sqoop-${SQOOP_VERSION}.tar.gz | head -n 10 \
    && tar xzf sqoop-${SQOOP_VERSION}.tar.gz -C /usr/ || echo "Failed to extract Sqoop"
RUN ls -l /usr/
RUN mv /usr/sqoop-${SQOOP_VERSION} /usr/sqoop || echo "Failed to move Sqoop directory"
RUN rm sqoop-${SQOOP_VERSION}.tar.gz

WORKDIR $SPARK_HOME
COPY load-spark-env.sh $SPARK_HOME/bin
RUN chmod +x $SPARK_HOME/bin/load-spark-env.sh

CMD ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
